# name: "Release"

<<<<<<< Updated upstream
# on:
#   push:
#     # tags:
#     #   - "**"±TODO:

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.13.x"
#           channel: "stable"
#       - name: Setup flutter
#         run: flutter pub get
#       - name: build
#         run: |
#           cd example
#           flutter build web -o ../build --no-tree-shake-icons --base-href "/zds_flutter/"
#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           folder: build
#       - name: Publish
#         run: |
#           dart format .
#           dart fix --apply
#           dart pub publish
=======
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
jobs:
  clean_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.x"
          channel: "stable"
      - name: Setup flutter
        run: flutter pub get
      - name: build
        run: |
          cd example
          flutter build web -o ../build --no-tree-shake-icons --base-href "/zds_flutter/"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
      - name: Publish
        run: |
          dart format .
          dart fix --apply
          name: Publish to pub.dev
  publish:
    needs: clean_build
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: "pub.dev"
>>>>>>> Stashed changes
